# Generated by Django 2.2 on 2019-06-14 23:30

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('name_slug', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='nombre')),
                ('size', models.CharField(max_length=25, verbose_name='talla')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='precio')),
                ('quantity', models.IntegerField(default=0, verbose_name='cantidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('code', models.SlugField(max_length=25, verbose_name='codigo')),
                ('prod_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='precio produccion')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.Institution', verbose_name='institucion')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=25, verbose_name='descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, max_length=140, verbose_name='comentarios')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='abono')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='descuento')),
                ('due_date', models.DateField(default=datetime.datetime(2019, 6, 29, 18, 30, 51, 747646), verbose_name='Fecha de entrega')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mystore.Client', verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Qty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('pending', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='mystore.Qty', to='mystore.Item'),
        ),
    ]
