# Generated by Django 2.2 on 2019-06-19 02:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_auto_20190614_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 3, 21, 42, 48, 824261), verbose_name='Fecha de entrega'),
        ),
    ]
