# Generated by Django 2.2 on 2019-06-22 13:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_auto_20190618_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_ordered',
            field=models.IntegerField(default=0, verbose_name='cantidad ordenada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 7, 8, 35, 39, 348570), verbose_name='Fecha de entrega'),
        ),
    ]
