# Generated by Django 2.2 on 2019-06-22 19:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0008_auto_20190622_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(choices=[(False, 'Borrador'), (True, 'Confirmado')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 7, 14, 52, 21, 269091), verbose_name='Fecha de entrega'),
        ),
    ]
