# Generated by Django 2.2 on 2019-06-24 18:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_auto_20190622_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_needed',
            field=models.IntegerField(default=0, verbose_name='cantidad necesitada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 13, 46, 56, 609662), verbose_name='Fecha de entrega'),
        ),
    ]
