# Generated by Django 2.2 on 2019-07-04 01:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_auto_20190624_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 18, 20, 58, 30, 984033), verbose_name='Fecha de entrega'),
        ),
    ]
