# Generated by Django 2.2 on 2019-07-04 02:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_auto_20190703_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='saldo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 18, 21, 34, 43, 643356), verbose_name='Fecha de entrega'),
        ),
    ]
