# Generated by Django 2.2 on 2019-07-18 14:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0013_auto_20190703_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 2, 9, 46, 29, 226226), help_text='ejemplo: 2019-05-28', verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(blank=True, max_length=140, verbose_name='descripcion / notas'),
        ),
    ]
