# Generated by Django 2.2 on 2019-07-18 14:54

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_auto_20190718_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='item',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.Institution', verbose_name='institución'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prod_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='precio producción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 2, 9, 54, 56, 904511), help_text='ejemplo: 2019-05-28', verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(blank=True, max_length=140, verbose_name='descripción / notas'),
        ),
    ]
