# Generated by Django 2.2 on 2019-07-18 14:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0015_auto_20190718_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 2, 9, 55, 19, 951288), help_text='ejemplo: 2019-05-28', verbose_name='Fecha de entrega'),
        ),
    ]
