# Generated by Django 2.2 on 2019-07-24 19:45

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0017_auto_20190724_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 14, 44, 53, 506945), help_text='ejemplo: 2019-05-28', verbose_name='Fecha de entrega'),
        ),
    ]
