# Generated by Django 2.2 on 2019-07-25 14:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0018_auto_20190724_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 9, 9, 3, 5, 72422), help_text='ejemplo: 2019-05-28', verbose_name='Fecha de entrega'),
        ),
    ]
