# Generated by Django 2.2 on 2019-10-29 19:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0019_auto_20190725_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institución/Categoria', 'verbose_name_plural': 'Instituciones/Categoria'},
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.SlugField(max_length=90, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=90, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 14, 43, 59, 389775), help_text='ejemplo: 2019-05-28', verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='abono'),
        ),
    ]
