# Generated by Django 2.2 on 2019-10-30 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0021_auto_20191030_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 12, 18, 31, 429689), help_text='ejemplo: 2019-05-28', verbose_name='Fecha de entrega'),
        ),
    ]
